from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.db.models import Alert, Observation, Patient, Prediction
from app.api.auth import require_role
from app.db.models import User

router = APIRouter()


@router.get("/patient/{patient_code}")
def get_patient_report(
    patient_code: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(require_role("admin", "clinician", "researcher")),
):
    patient = (
        db.query(Patient)
        .filter(Patient.patient_code == patient_code)
        .first()
    )

    if not patient:
        raise HTTPException(
            status_code=404,
            detail="Patient not found."
        )

    predictions = (
        db.query(Prediction, Observation)
        .outerjoin(Observation, Prediction.observation_id == Observation.id)
        .filter(Prediction.patient_id == patient.id)
        .order_by(Prediction.created_at.asc())
        .all()
    )

    if not predictions:
        return {
            "patient": {
                "id": patient.id,
                "patient_code": patient.patient_code,
                "age": patient.age,
                "gender": patient.gender,
                "unit1": patient.unit1,
                "unit2": patient.unit2,
                "created_at": patient.created_at,
            },
            "latest_prediction": None,
            "timeline": [],
            "active_alerts": [],
            "clinical_safety_note": (
                "This report is generated by a clinical decision support "
                "prototype and must not replace clinician judgment."
            )
        }

    latest_prediction, latest_observation = predictions[-1]

    timeline = []

    for prediction, observation in predictions:
        observation_data = observation.observation_data if observation else {}

        timeline.append({
            "prediction_id": prediction.id,
            "created_at": prediction.created_at,
            "iculos": observation.iculos if observation else None,
            "calibrated_probability": prediction.calibrated_probability,
            "risk_level": prediction.risk_level,
            "final_alert": prediction.final_alert,
            "sirs_score": prediction.sirs_score,
            "priority": prediction.priority,
            "observation": {
                "HR": observation_data.get("HR"),
                "Temp": observation_data.get("Temp"),
                "MAP": observation_data.get("MAP"),
                "Resp": observation_data.get("Resp"),
                "Lactate": observation_data.get("Lactate"),
                "WBC": observation_data.get("WBC"),
                "ICULOS": observation_data.get("ICULOS"),
            }
        })

    active_alerts = (
        db.query(Alert)
        .filter(Alert.patient_id == patient.id)
        .filter(Alert.is_active == True)
        .order_by(Alert.created_at.desc())
        .all()
    )

    latest_observation_data = (
        latest_observation.observation_data if latest_observation else {}
    )

    return {
        "patient": {
            "id": patient.id,
            "patient_code": patient.patient_code,
            "age": patient.age,
            "gender": patient.gender,
            "unit1": patient.unit1,
            "unit2": patient.unit2,
            "created_at": patient.created_at,
        },
        "latest_prediction": {
            "id": latest_prediction.id,
            "created_at": latest_prediction.created_at,
            "model_name": latest_prediction.model_name,
            "model_version": latest_prediction.model_version,
            "raw_probability": latest_prediction.raw_probability,
            "calibrated_probability": latest_prediction.calibrated_probability,
            "threshold": latest_prediction.threshold,
            "risk_level": latest_prediction.risk_level,
            "ai_alert": latest_prediction.ai_alert,
            "final_alert": latest_prediction.final_alert,
            "priority": latest_prediction.priority,
            "recommendation": latest_prediction.recommendation,
            "sirs_score": latest_prediction.sirs_score,
            "sirs_positive": latest_prediction.sirs_positive,
            "top_risk_factors": latest_prediction.top_risk_factors,
            "top_protective_factors": latest_prediction.top_protective_factors,
            "latest_observation": latest_observation_data,
        },
        "timeline": timeline,
        "active_alerts": [
            {
                "id": alert.id,
                "priority": alert.priority,
                "message": alert.message,
                "created_at": alert.created_at,
                "is_active": alert.is_active,
            }
            for alert in active_alerts
        ],
        "clinical_safety_note": (
            "This report is generated by a clinical decision support prototype. "
            "It is intended to support, not replace, clinician judgment. "
            "Clinical assessment, local protocols, and patient context must always "
            "be considered before making treatment decisions."
        )
    }